"""Input domain: dispatching synthetic input events to the page."""

from typing import Any

from cdpwave.domains.base import BaseDomain

_VALID_KEY_TYPES = frozenset({
    "keyDown",
    "keyUp",
    "rawKeyDown",
    "char",
})
_VALID_MOUSE_TYPES = frozenset({
    "mousePressed",
    "mouseReleased",
    "mouseMoved",
    "mouseWheel",
})
_VALID_MOUSE_BUTTONS = frozenset({
    "none",
    "left",
    "middle",
    "right",
    "back",
    "forward",
})
_VALID_TOUCH_EVENT_TYPES = frozenset({
    "mouseWheel",
    "mouseMoved",
    "mousePressed",
    "mouseReleased",
})
_VALID_GESTURE_SOURCE_TYPES = frozenset({"default", "touch", "mouse"})


class InputDomain(BaseDomain):
    """Wrapper for the CDP Input domain.

    Provides methods for dispatching synthetic input events (mouse,
    keyboard, touch, drag) to the browser page.
    """

    async def dispatch_key_event(
        self,
        type: str,
        key: str | None = None,
        code: str | None = None,
        key_identifier: str | None = None,
        windows_virtual_key_code: int | None = None,
        native_virtual_key_code: int | None = None,
        text: str | None = None,
        unmodified_text: str | None = None,
        modifiers: int | None = None,
        timestamp: float | None = None,
        auto_repeat: bool | None = None,
        is_keypad: bool | None = None,
        is_system_key: bool | None = None,
        location: int | None = None,
        commands: list[str] | None = None,
    ) -> dict[str, Any]:
        """Dispatch a key event to the page.

        Args:
            type: Event type (``"keyDown"``, ``"keyUp"``, ``"rawKeyDown"``,
                ``"char"``).
            key: Key value (e.g. ``"a"``, ``"Enter"``).
            code: DOM code (e.g. ``"KeyA"``, ``"Enter"``).
            key_identifier: Unique key identifier (e.g. ``"U+0041"``).
            windows_virtual_key_code: Windows virtual key code.
            native_virtual_key_code: Native virtual key code.
            text: Text generated by the key event.
            unmodified_text: Text without modifier interpretation.
            modifiers: Bitmask of modifiers (1=Alt, 2=Ctrl, 4=Meta, 8=Shift).
            timestamp: Time of the event in seconds.
            auto_repeat: Whether the key is auto-repeating.
            is_keypad: Whether the event is from a keypad.
            is_system_key: Whether the event is a system key.
            location: Key location (0=standard, 1=left, 2=right, 3=numpad).
            commands: Edit commands to execute.

        Returns:
            Response dict from the CDP command.
        """
        if not isinstance(type, str):
            raise TypeError("type must be a str")
        if type not in _VALID_KEY_TYPES:
            raise ValueError(
                "type must be 'keyDown', 'keyUp', 'rawKeyDown', or 'char'"
            )
        params: dict[str, Any] = {"type": type}
        if key is not None:
            params["key"] = key
        if code is not None:
            params["code"] = code
        if key_identifier is not None:
            params["keyIdentifier"] = key_identifier
        if windows_virtual_key_code is not None:
            params["windowsVirtualKeyCode"] = windows_virtual_key_code
        if native_virtual_key_code is not None:
            params["nativeVirtualKeyCode"] = native_virtual_key_code
        if text is not None:
            params["text"] = text
        if unmodified_text is not None:
            params["unmodifiedText"] = unmodified_text
        if modifiers is not None:
            params["modifiers"] = modifiers
        if timestamp is not None:
            params["timestamp"] = timestamp
        if auto_repeat is not None:
            params["autoRepeat"] = auto_repeat
        if is_keypad is not None:
            params["isKeypad"] = is_keypad
        if is_system_key is not None:
            params["isSystemKey"] = is_system_key
        if location is not None:
            params["location"] = location
        if commands is not None:
            params["commands"] = commands
        return await self._call("Input.dispatchKeyEvent", params)

    async def dispatch_mouse_event(
        self,
        type: str,
        x: float = 0,
        y: float = 0,
        *,
        button: str = "none",
        buttons: int = 0,
        click_count: int | None = None,
        delta_x: float | None = None,
        delta_y: float | None = None,
        modifiers: int | None = None,
        timestamp: float | None = None,
        force: float | None = None,
        tangential_pressure: float | None = None,
        tilt_x: float | None = None,
        tilt_y: float | None = None,
        twist: int | None = None,
        pointer_type: str | None = None,
    ) -> dict[str, Any]:
        """Dispatch a mouse event to the page.

        Args:
            type: Event type (``"mousePressed"``, ``"mouseReleased"``,
                ``"mouseMoved"``, ``"mouseWheel"``).
            x: X coordinate relative to the viewport.
            y: Y coordinate relative to the viewport.
            button: Mouse button (``"none"``, ``"left"``, ``"middle"``,
                ``"right"``, ``"back"``, ``"forward"``).
            buttons: Bitmask of pressed buttons.
            click_count: Number of consecutive clicks.
            delta_x: Horizontal scroll delta (for ``mouseWheel``).
            delta_y: Vertical scroll delta (for ``mouseWheel``).
            modifiers: Bitmask of modifiers.
            timestamp: Time of the event in seconds.
            force: Normalized pressure [0,1].
            tangential_pressure: Normalized tangential pressure [-1,1].
            tilt_x: Plane angle between Y-Z plane and stylus axis [-90,90].
            tilt_y: Plane angle between X-Z plane and stylus axis [-90,90].
            twist: Clockwise rotation of stylus [0,359].
            pointer_type: Pointer type (default ``"mouse"``).

        Returns:
            Response dict from the CDP command.
        """
        if not isinstance(type, str):
            raise TypeError("type must be a str")
        if type not in _VALID_MOUSE_TYPES:
            raise ValueError(
                "type must be 'mousePressed', 'mouseReleased', "
                "'mouseMoved', or 'mouseWheel'"
            )
        if not isinstance(button, str):
            raise TypeError("button must be a str")
        if button not in _VALID_MOUSE_BUTTONS:
            raise ValueError(
                "button must be 'none', 'left', 'middle', 'right', "
                "'back', or 'forward'"
            )
        params: dict[str, Any] = {
            "type": type,
            "x": x,
            "y": y,
            "button": button,
            "buttons": buttons,
        }
        if click_count is not None:
            params["clickCount"] = click_count
        if delta_x is not None:
            params["deltaX"] = delta_x
        if delta_y is not None:
            params["deltaY"] = delta_y
        if modifiers is not None:
            params["modifiers"] = modifiers
        if timestamp is not None:
            params["timestamp"] = timestamp
        if force is not None:
            params["force"] = force
        if tangential_pressure is not None:
            params["tangentialPressure"] = tangential_pressure
        if tilt_x is not None:
            params["tiltX"] = tilt_x
        if tilt_y is not None:
            params["tiltY"] = tilt_y
        if twist is not None:
            params["twist"] = twist
        if pointer_type is not None:
            params["pointerType"] = pointer_type
        return await self._call("Input.dispatchMouseEvent", params)

    async def dispatch_touch_event(
        self,
        type: str,
        touch_points: list[dict[str, Any]],
        modifiers: int | None = None,
        timestamp: float | None = None,
    ) -> dict[str, Any]:
        """Dispatch a touch event to the page.

        Args:
            type: Event type (``"touchStart"``, ``"touchEnd"``,
                ``"touchMove"``, ``"touchCancel"``).
            touch_points: List of touch point dicts with ``x``, ``y``,
                ``radiusX``, ``radiusY``, ``force``, ``id``.
            modifiers: Bitmask of modifiers.
            timestamp: Time of the event in seconds.

        Returns:
            Response dict from the CDP command.
        """
        params: dict[str, Any] = {
            "type": type,
            "touchPoints": touch_points,
        }
        if modifiers is not None:
            params["modifiers"] = modifiers
        if timestamp is not None:
            params["timestamp"] = timestamp
        return await self._call("Input.dispatchTouchEvent", params)

    async def dispatch_drag_event(
        self,
        type: str,
        x: float,
        y: float,
        data: dict[str, Any],
        modifiers: int | None = None,
    ) -> dict[str, Any]:
        """Dispatch a drag event to the page.

        Args:
            type: Event type (``"dragEnter"``, ``"dragOver"``,
                ``"drop"``, ``"dragCancel"``).
            x: X coordinate relative to the viewport.
            y: Y coordinate relative to the viewport.
            data: Drag data dict containing ``items``, ``dragOperationsMask``,
                and ``files``.
            modifiers: Bitmask of modifiers (Alt=1, Ctrl=2, Meta=4, Shift=8).

        Returns:
            Response dict from the CDP command.
        """
        params: dict[str, Any] = {
            "type": type,
            "x": x,
            "y": y,
            "data": data,
        }
        if modifiers is not None:
            params["modifiers"] = modifiers
        return await self._call("Input.dispatchDragEvent", params)

    async def insert_text(self, text: str) -> dict[str, Any]:
        """Insert text as if it was typed with a physical keyboard.

        Args:
            text: The text to insert.

        Returns:
            Response dict from the CDP command.
        """
        return await self._call("Input.insertText", {"text": text})

    async def type_text(self, text: str) -> None:
        """Type text by sending individual ``char`` key events.

        Unlike ``insert_text``, this dispatches proper key events for
        each character, which is required for some input fields that
        listen to ``keydown``/``keypress`` events.

        Args:
            text: The text to type.
        """
        for char in text:
            await self.dispatch_key_event("char", text=char)

    async def ime_set_composition(
        self,
        text: str,
        selection_start: int,
        selection_end: int,
        replacement_start: int | None = None,
        replacement_end: int | None = None,
    ) -> dict[str, Any]:
        """Set the IME composition for the current input context.

        Args:
            text: The composition text.
            selection_start: Start of the selection in the composition.
            selection_end: End of the selection in the composition.
            replacement_start: Start of the replacement range.
            replacement_end: End of the replacement range.

        Returns:
            Response dict from the CDP command.
        """
        params: dict[str, Any] = {
            "text": text,
            "selectionStart": selection_start,
            "selectionEnd": selection_end,
        }
        if replacement_start is not None:
            params["replacementStart"] = replacement_start
        if replacement_end is not None:
            params["replacementEnd"] = replacement_end
        return await self._call("Input.imeSetComposition", params)

    async def cancel_dragging(self) -> dict[str, Any]:
        """Cancel any ongoing drag operation on the page.

        Aborts the current drag-and-drop sequence, releasing any
        held elements and resetting the drag state.

        Returns:
            Response dict from the CDP.
        """
        return await self._call("Input.cancelDragging")

    async def set_intercept_drags(self, enabled: bool) -> dict[str, Any]:
        """Enable or disable drag interception.

        Args:
            enabled: Whether to intercept drag events.
        """
        return await self._call(
            "Input.setInterceptDrags",
            {"enabled": enabled},
        )

    async def synthesize_pinch_gesture(
        self,
        x: float,
        y: float,
        scale_factor: float,
        relative_speed: int = 800,
        gesture_source_type: str = "default",
    ) -> dict[str, Any]:
        """Synthesize a pinch gesture at a point.

        Args:
            x: X coordinate of the gesture center.
            y: Y coordinate of the gesture center.
            scale_factor: Relative scale factor (>1 zoom in, <1 zoom out).
            relative_speed: Speed of the gesture (pixels per second).
            gesture_source_type: Source type (``"default"``, ``"touch"``,
                ``"mouse"``).

        Returns:
            Response dict from the CDP command.
        """
        if not isinstance(gesture_source_type, str):
            raise TypeError("gesture_source_type must be a str")
        if gesture_source_type not in _VALID_GESTURE_SOURCE_TYPES:
            raise ValueError(
                "gesture_source_type must be 'default', 'touch', or 'mouse'"
            )
        return await self._call(
            "Input.synthesizePinchGesture",
            {
                "x": x,
                "y": y,
                "scaleFactor": scale_factor,
                "relativeSpeed": relative_speed,
                "gestureSourceType": gesture_source_type,
            },
        )

    async def synthesize_scroll_gesture(
        self,
        x: float,
        y: float,
        x_distance: float = 0.0,
        y_distance: float = 0.0,
        x_overscroll: float = 0.0,
        y_overscroll: float = 0.0,
        prevent_fling: bool = True,
        speed: int = 800,
        gesture_source_type: str = "default",
        repeat_count: int = 0,
        repeat_delay_ms: int = 250,
        interaction_marker_name: str | None = None,
    ) -> dict[str, Any]:
        """Synthesize a scroll gesture at a point.

        Args:
            x: X coordinate of the gesture start.
            y: Y coordinate of the gesture start.
            x_distance: Horizontal scroll distance.
            y_distance: Vertical scroll distance.
            x_overscroll: Horizontal overscroll distance.
            y_overscroll: Vertical overscroll distance.
            prevent_fling: Whether to prevent fling after scroll.
            speed: Speed of the gesture (pixels per second).
            gesture_source_type: Source type (``"default"``, ``"touch"``,
                ``"mouse"``).
            repeat_count: Number of times to repeat the gesture.
            repeat_delay_ms: Delay between repeats in milliseconds.
            interaction_marker_name: Name of the interaction markers
                to generate, if not empty.

        Returns:
            Response dict from the CDP command.
        """
        if not isinstance(gesture_source_type, str):
            raise TypeError("gesture_source_type must be a str")
        if gesture_source_type not in _VALID_GESTURE_SOURCE_TYPES:
            raise ValueError(
                "gesture_source_type must be 'default', 'touch', or 'mouse'"
            )
        params: dict[str, Any] = {
            "x": x,
            "y": y,
            "xDistance": x_distance,
            "yDistance": y_distance,
            "xOverscroll": x_overscroll,
            "yOverscroll": y_overscroll,
            "preventFling": prevent_fling,
            "speed": speed,
            "gestureSourceType": gesture_source_type,
            "repeatCount": repeat_count,
            "repeatDelayMs": repeat_delay_ms,
        }
        if interaction_marker_name is not None:
            params["interactionMarkerName"] = interaction_marker_name
        return await self._call(
            "Input.synthesizeScrollGesture",
            params,
        )

    async def emulate_touch_from_mouse_event(
        self,
        type: str,
        x: int,
        y: int,
        button: str = "none",
        click_count: int | None = None,
        delta_x: float | None = None,
        delta_y: float | None = None,
        modifiers: int | None = None,
        timestamp: float | None = None,
    ) -> dict[str, Any]:
        """Emulate a touch event from a mouse event.

        Args:
            type: Event type (``"mouseWheel"``, ``"mouseMoved"``,
                ``"mousePressed"``, ``"mouseReleased"``).
            x: X coordinate of the mouse pointer in DIP.
            y: Y coordinate of the mouse pointer in DIP.
            button: Mouse button. Only ``"none"``, ``"left"``,
                ``"right"`` are supported.
            click_count: Number of consecutive clicks.
            delta_x: Horizontal scroll delta in DIP.
            delta_y: Vertical scroll delta in DIP.
            modifiers: Bitmask of modifiers.
            timestamp: Time of the event in seconds.

        Returns:
            Response dict from the CDP command.
        """
        if not isinstance(type, str):
            raise TypeError("type must be a str")
        if type not in _VALID_TOUCH_EVENT_TYPES:
            raise ValueError(
                "type must be 'mouseWheel', 'mouseMoved', "
                "'mousePressed', or 'mouseReleased'"
            )
        if not isinstance(button, str):
            raise TypeError("button must be a str")
        if button not in _VALID_MOUSE_BUTTONS:
            raise ValueError(
                "button must be 'none', 'left', 'middle', 'right', "
                "'back', or 'forward'"
            )
        params: dict[str, Any] = {
            "type": type,
            "x": x,
            "y": y,
            "button": button,
        }
        if click_count is not None:
            params["clickCount"] = click_count
        if delta_x is not None:
            params["deltaX"] = delta_x
        if delta_y is not None:
            params["deltaY"] = delta_y
        if modifiers is not None:
            params["modifiers"] = modifiers
        if timestamp is not None:
            params["timestamp"] = timestamp
        return await self._call("Input.emulateTouchFromMouseEvent", params)

    async def set_ignore_input_events(
        self,
        ignore: bool,
    ) -> dict[str, Any]:
        """Ignore or process input events.

        Args:
            ignore: Whether to ignore input events.
        """
        return await self._call(
            "Input.setIgnoreInputEvents",
            {"ignore": ignore},
        )

    async def synthesize_tap_gesture(
        self,
        x: float,
        y: float,
        duration: int = 50,
        tap_count: int = 1,
        gesture_source_type: str = "default",
    ) -> dict[str, Any]:
        """Synthesize a tap gesture at a point.

        Args:
            x: X coordinate of the tap.
            y: Y coordinate of the tap.
            duration: Duration of the tap in milliseconds.
            tap_count: Number of consecutive taps.
            gesture_source_type: Source type (``"default"``, ``"touch"``,
                ``"mouse"``).

        Returns:
            Response dict from the CDP command.
        """
        if not isinstance(gesture_source_type, str):
            raise TypeError("gesture_source_type must be a str")
        if gesture_source_type not in _VALID_GESTURE_SOURCE_TYPES:
            raise ValueError(
                "gesture_source_type must be 'default', 'touch', or 'mouse'"
            )
        return await self._call(
            "Input.synthesizeTapGesture",
            {
                "x": x,
                "y": y,
                "duration": duration,
                "tapCount": tap_count,
                "gestureSourceType": gesture_source_type,
            },
        )
