"""cdpwave — Chrome DevTools Protocol client for Python.

Public API exports for the cdpwave package.
"""

from importlib.metadata import version as _version

__version__ = _version("cdpwave")

from cdpwave.client import BrowserContext, CDPClient, CDPSession
from cdpwave.events.dispatcher import EventDispatcher
from cdpwave.events.handlers import EventHandler, Subscription
from cdpwave.exceptions import (
    BrowserNotFoundError,
    CDPError,
    CommandError,
    CommandTimeoutError,
    ConnectionClosedError,
    ConnectionReconnectError,
    DiscoveryError,
    LaunchError,
    LaunchTimeoutError,
    ProtocolError,
    SessionClosedError,
)
from cdpwave.types import (
    DOMDescribeNodeResult,
    DOMGetDocumentResult,
    DOMGetOuterHTMLResult,
    DOMGetSearchResultsResult,
    DOMNode,
    DOMQuerySelectorResult,
    DOMResolveNodeResult,
    DOMSearchResult,
    ExceptionDetails,
    NetworkCookie,
    NetworkGetCookiesResult,
    NetworkGetRequestPostDataResult,
    NetworkGetResponseBodyResult,
    NetworkLoadNetworkResourceResult,
    PageAddScriptToEvaluateOnNewDocumentResult,
    PageCaptureScreenshotResult,
    PageGetFrameTreeResult,
    PageGetLayoutMetricsResult,
    PageGetNavigationHistoryResult,
    PageGetResourceContentResult,
    PageGetResourceTreeResult,
    PageNavigateResult,
    PagePrintToPDFResult,
    RemoteObject,
    RuntimeAwaitPromiseResult,
    RuntimeCallFunctionOnResult,
    RuntimeCompileScriptResult,
    RuntimeEvaluateResult,
    RuntimeGetExceptionDetailsResult,
    RuntimeGetHeapUsageResult,
    RuntimeGetIsolateIdResult,
    RuntimeGetPropertiesResult,
    RuntimeGlobalLexicalScopeNamesResult,
    RuntimeQueryObjectsResult,
    RuntimeRunScriptResult,
    TargetAttachToTargetResult,
    TargetCreateTargetResult,
    TargetGetTargetInfoResult,
    TargetGetTargetsResult,
)

__all__ = [
    "BrowserContext",
    "BrowserNotFoundError",
    "CDPClient",
    "CDPError",
    "CDPSession",
    "CommandError",
    "CommandTimeoutError",
    "ConnectionClosedError",
    "ConnectionReconnectError",
    "DOMDescribeNodeResult",
    "DOMGetDocumentResult",
    "DOMGetOuterHTMLResult",
    "DOMGetSearchResultsResult",
    "DOMNode",
    "DOMQuerySelectorResult",
    "DOMResolveNodeResult",
    "DOMSearchResult",
    "DiscoveryError",
    "EventDispatcher",
    "EventHandler",
    "ExceptionDetails",
    "LaunchError",
    "LaunchTimeoutError",
    "NetworkCookie",
    "NetworkGetCookiesResult",
    "NetworkGetRequestPostDataResult",
    "NetworkGetResponseBodyResult",
    "NetworkLoadNetworkResourceResult",
    "PageAddScriptToEvaluateOnNewDocumentResult",
    "PageCaptureScreenshotResult",
    "PageGetFrameTreeResult",
    "PageGetLayoutMetricsResult",
    "PageGetNavigationHistoryResult",
    "PageGetResourceContentResult",
    "PageGetResourceTreeResult",
    "PageNavigateResult",
    "PagePrintToPDFResult",
    "ProtocolError",
    "RemoteObject",
    "RuntimeAwaitPromiseResult",
    "RuntimeCallFunctionOnResult",
    "RuntimeCompileScriptResult",
    "RuntimeEvaluateResult",
    "RuntimeGetExceptionDetailsResult",
    "RuntimeGetHeapUsageResult",
    "RuntimeGetIsolateIdResult",
    "RuntimeGetPropertiesResult",
    "RuntimeGlobalLexicalScopeNamesResult",
    "RuntimeQueryObjectsResult",
    "RuntimeRunScriptResult",
    "SessionClosedError",
    "Subscription",
    "TargetAttachToTargetResult",
    "TargetCreateTargetResult",
    "TargetGetTargetInfoResult",
    "TargetGetTargetsResult",
    "__version__",
]